# Generated by Django 3.2.2 on 2021-05-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20210508_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='subject',
            new_name='club',
        ),
    ]
