# Generated by Django 3.2.2 on 2021-05-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_rename_subject_trainer_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsgroup',
            old_name='course',
            new_name='trainer',
        ),
    ]
