# Generated by Django 3.2.2 on 2021-05-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_rename_course_studentsgroup_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='clubs.studentsgroup'),
        ),
    ]
