# Generated by Django 3.2.2 on 2021-05-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20210510_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d'),
        ),
    ]
