# Generated by Django 3.2.2 on 2021-05-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_alter_studentprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(choices=[('Vasya Pupkin', 'Vasya Pupkin'), ('Dima Zoo', 'Dima Zoo'), ('Eugen Nik', 'Eugen Nik'), ('Sergey Voo', 'Sergey Voo'), ('Илья Знаменский', 'Илья Знаменский')], default='None', max_length=90),
        ),
    ]
